version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7  # Adjust based on your Python version
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/137068254659

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t housing_price .
      - docker tag housing_price:latest public.ecr.aws/137068254659/housing_price:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR Public...
      - docker push public.ecr.aws/137068254659/housing_price:latest

artifacts:
  files:
    - '**/*'
